#???
spring.datasource.target.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.target.jdbc-url=jdbc:mysql://xx:3306/db1?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true
spring.datasource.target.username=username
spring.datasource.target.password=passworld

#?????
spring.datasource.source.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.source.jdbc-url=jdbc:mysql://xx:3306/db2?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true
spring.datasource.source.username=username
spring.datasource.source.password=password